import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#42465a',
        'on-surface-variant': '#3d4a42',
        'on-primary': '#ffffff',
        'error': '#ba1a1a',
        'on-secondary': '#ffffff',
        'on-background': '#1a1c1a',
        'on-tertiary-container': '#45495e',
        'tertiary-container': '#b6b9d2',
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#bfc4eb',
        'on-primary-fixed': '#002114',
        'surface-container': '#efeeeb',
        'tertiary': '#595d73',
        'surface-variant': '#e3e2e0',
        'on-surface': '#1a1c1a',
        'error-container': '#ffdad6',
        'surface-bright': '#faf9f6',
        'surface-tint': '#006c4c',
        'outline-variant': '#bccac0',
        'primary': '#006c4c',
        'inverse-on-surface': '#f2f1ee',
        'primary-fixed': '#81f9c5',
        'primary-fixed-dim': '#63dcaa',
        'surface-container-high': '#e9e8e5',
        'on-secondary-fixed': '#131937',
        'surface': '#faf9f6',
        'on-error': '#ffffff',
        'background': '#faf9f6',
        'tertiary-fixed-dim': '#c2c5de',
        'outline': '#6d7a72',
        'surface-container-highest': '#e3e2e0',
        'secondary': '#575c7e',
        'inverse-primary': '#63dcaa',
        'on-error-container': '#93000a',
        'on-primary-fixed-variant': '#005138',
        'on-secondary-fixed-variant': '#3f4565',
        'on-primary-container': '#00553b',
        'tertiary-fixed': '#dee1fb',
        'surface-dim': '#dbdad7',
        'surface-container-low': '#f4f3f1',
        'primary-container': '#55cf9e',
        'on-secondary-container': '#565b7d',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed': '#dee1ff',
        'inverse-surface': '#2f312f',
        'on-tertiary-fixed': '#161b2d',
        'secondary-container': '#d0d5fd',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['var(--font-manrope)', 'system-ui', 'sans-serif'],
        body: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        label: ['var(--font-inter)', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
};

export default config;
